name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Asegúrate de que estás usando una versión compatible con ESLint 9

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint .
